version: '3.8'
name: fiapeats-ms-pedido
services:
  mongodb:
    image: mongo:latest
    profiles: [database, envfull]
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pass
    volumes:
      - mongodb_data:/data/db
    networks:
      - net-mongodb-ms-pedido

  mongo-express:
    image: mongo-express:latest
    profiles: [database, envfull]
    container_name: mongo-express
    restart: always
    depends_on:
      - mongodb
    ports:
      - "8090:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      ME_CONFIG_MONGODB_SERVER: mongodb
    networks:
      - net-mongodb-ms-pedido

  ms-pedido-api:
    container_name: api-ms-pedido
    build:
      context: .
      args:
        JAR_VERSION: "1.0.0"
      dockerfile: Dockerfile
    profiles: [ app, envfull ]
    restart: on-failure
    ports:
      - "8084:8080"
    depends_on:
      - mongodb
    env_file: "variables/ambient.env"
    networks:
      - net-mongodb-ms-pedido
      - fiapeats-all-ms-network

networks:
  net-mongodb-ms-pedido:
    driver: bridge
  fiapeats-all-ms-network:
    name: fiapeats-all-ms-network
    driver: bridge

volumes:
  mongodb_data:
    driver: local
