server:
  port: 8082
  servlet:
    context-path: /fiapeats

spring:
  application:
    name: tc-fiapeats-ms-pedido
  data:
    mongodb:
      host: ${DATASOURCE_HOST}
      port: ${DATASOURCE_PORT}
      database: ${DATASOURCE}
      username: ${DATASOURCE_USERNAME}
      password: ${DATASOURCE_PASSWORD}
      authentication-database: ${DATASOURCE_AUTH}


logging:
  level:
    feign: DEBUG
    feign.client: DEBUG
    org.springframework.cloud.openfeign: DEBUG
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG

feign:
  client:
    url: ${FEIGN_BASE_URL}




