name: Deploy Automatizado para Kubernetes
on:
  pull_request:
    branches:
      - main
permissions:
  contents: write
jobs:
  setup-jdk:
    runs-on: ubuntu-latest
    outputs:
      jdk-path: ${{ steps.setup-java.outputs.jdkFile }}
    steps:
      - name: Checkout código
        uses: actions/checkout@v3
      - name: Usar JDK configurado
        run: |
          echo "JDK configurado em: ${{ needs.setup-jdk.outputs.jdk-path }}"
  compile:
    runs-on: ubuntu-latest
    needs: setup-jdk
    steps:
      - name: Checkout código
        uses: actions/checkout@v3
      - name: Usar JDK configurado
        run: |
          echo "JDK configurado em: ${{ needs.setup-jdk.outputs.jdk-path }}"
      - name: Detectar alterações
        run: |
          if git diff --quiet HEAD^ HEAD -- .; then
            echo "CHANGED=false" >> $GITHUB_ENV
          else
            echo "CHANGED=true" >> $GITHUB_ENV
          fi
      - name: Atualizar versão do pom.xml
        if: env.CHANGED == 'true' && github.ref == 'refs/heads/main'
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"
          NEW_VERSION="$MAJOR.$MINOR.$((PATCH+1))"
          # Atualizar o pom.xml
          mvn versions:set -DnewVersion=$NEW_VERSION
          mvn versions:commit
      - name: Commit alterações
        if: github.ref == 'refs/heads/main'  # Só executa no branch main
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add pom.xml
          git commit -m "Atualiza versão para $NEW_VERSION"

      - name: Push alterações
        if: github.ref == 'refs/heads/main'  # Só executa no branch main
        run: |
          git push origin ${{ github.ref }}

      - name: Build projeto
        run: mvn clean package -Dmaven.test.skip=true

      - name: Extrair versão do projeto
        id: project
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

  unit-tests:
    needs: compile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Usar JDK configurado
        run: |
          echo "JDK configurado em: ${{ needs.setup-jdk.outputs.jdk-path }}"

      - name: Executar testes unitários
        run: mvn test -P!integration-test -P!system-test -P!performance-test

      - name: Gerar link do relatório de testes unitários
        run: |
          echo "Relatório de testes unitários disponível em: file://$(pwd)/target/surefire-reports/index.html" 

  sonarqube:
    runs-on: ubuntu-latest
    needs: [ unit-tests ]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu' # Alternative distribution options are available.
      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B test org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=fiapeats-msp_pedido
      - name: Check SonarQube Quality Gate
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: "https://sonarcloud.io"
        run: |
          SONAR_PROJECT_KEY="fiapeats-msp_pedido"
          PULL_REQUEST_NUMBER=${{ github.event.pull_request.number }}

          if [[ -n "$PULL_REQUEST_NUMBER" ]]; then
            QUALITY_GATE_URL="$SONAR_HOST_URL/api/qualitygates/project_status?projectKey=$SONAR_PROJECT_KEY&pullRequest=$PULL_REQUEST_NUMBER"
          else
            QUALITY_GATE_URL="$SONAR_HOST_URL/api/qualitygates/project_status?projectKey=$SONAR_PROJECT_KEY"
          fi

          echo "Consultando Quality Gate em: $QUALITY_GATE_URL"

          MAX_RETRIES=10
          RETRY_DELAY=10  # Segundos

          for ((i=1; i<=MAX_RETRIES; i++)); do
            STATUS=$(curl -s -u $SONAR_TOKEN: "$QUALITY_GATE_URL" | jq -r .projectStatus.status)

            if [[ "$STATUS" != "null" ]]; then
              break
            fi

            echo "SonarQube ainda não está pronto. Tentativa $i de $MAX_RETRIES..."
            sleep $RETRY_DELAY
          done

          echo "Quality Gate Status: $STATUS"

          if [[ "$STATUS" != "OK" ]]; then
            echo "❌ Quality Gate Failed!"
            exit 1
          fi

          echo "✅ Quality Gate Passed!"

  verify-aws:
    needs: sonarqube
    runs-on: ubuntu-latest
    steps:
      - name: Configurar AWS
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Verificar cluster EKS
        run: |
          aws eks describe-cluster --name eks-cluster --region us-east-1 || echo "Cluster não encontrado."

      - name: Logar no Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 980921733871.dkr.ecr.us-east-1.amazonaws.com

      - name: Validar repositório ECR
        run: |
          aws ecr describe-repositories --repository-names fiapeats-ms-pedido --region us-east-1 || \
          aws ecr create-repository --repository-name fiapeats-ms-pedido --region us-east-1

  publish-image:
    needs: verify-aws
    runs-on: ubuntu-latest
    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v3

      - name: Configurar credenciais AWS
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Obter AWS Account ID e versão
        id: get-account-id
        run: |
          ACCOUNT_ID=980921733871
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "AWS_ACCOUNT_ID=$ACCOUNT_ID" >> $GITHUB_ENV  

      - name: Atualizar configuração do Kubernetes
        run: |
          aws eks update-kubeconfig --name eks-cluster --region us-east-1
          kubectl cluster-info

      - name: Obter login no Amazon ECR
        run: |
          echo "Fazendo login no ECR da conta ${AWS_ACCOUNT_ID}..."
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com

      - name: Construir imagem Docker
        run: |
          # Captura a versão do projeto a partir do Maven
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)

          # Define o repositório da imagem
          IMAGE_REPO="${AWS_ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com/fiapeats-ms-pedido"

          echo "Versão detectada: $VERSION"

          # Builda a imagem Docker e passa a versão como build-arg
          docker build --build-arg JAR_VERSION=$VERSION -t $IMAGE_REPO:$VERSION .

          # Caso seja produção, também criar e push da tag 'latest'
          if [ "${{ github.event_name }}" == "pull_request" ] && [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "Ambiente de produção detectado. Criando tag 'latest' para a imagem Docker."
            docker tag $IMAGE_REPO:$VERSION $IMAGE_REPO:latest
          else
            echo "Ambiente de desenvolvimento detectado. Apenas a tag de versão será utilizada."
          fi


      - name: Push da imagem para o Amazon ECR
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          IMAGE_REPO="${AWS_ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com/fiapeats-ms-pedido"
          docker push $IMAGE_REPO:$VERSION
          
          # Tag e push para latest apenas para produção
          if [ "${{ github.event_name }}" == "pull_request" ] && [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "Fazendo merge na latest"
            docker tag $IMAGE_REPO:$VERSION $IMAGE_REPO:latest
            docker push $IMAGE_REPO:latest
          fi


      - name: Atualizar imagem do Deployment no Kubernetes
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "Versão detectada: $VERSION"
          IMAGE_REPO="${AWS_ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com/fiapeats-ms-pedido"
          
          # Determinar se o deploy é de produção
          if [ "${{ github.event_name }}" == "pull_request" ] && [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "Deploy no ambiente de produção. Atualizando com a imagem 'latest'..."
            docker tag $IMAGE_REPO:$VERSION $IMAGE_REPO:latest
            docker push $IMAGE_REPO:latest
            kubectl set image deployment/fiapeats-ms-pedido-deployment fiapeats-ms-pedido-container=$IMAGE_REPO:latest
          else
            echo "Deploy no ambiente de desenvolvimento. Atualizando com a imagem versionada..."
            kubectl set image deployment/fiapeats-ms-pedido-deployment fiapeats-ms-pedido-container=$IMAGE_REPO:$VERSION
          fi

  # Job para deploy no ambiente de produção
  deploy-production:
    needs: publish-image
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v3

      - name: Instalar kubectl
        uses: azure/setup-kubectl@v2.0
        with:
          version: 'v1.24.0'

      - name: Configurar credenciais AWS
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Atualizar configuração do Kubernetes
        run: |
          aws eks update-kubeconfig --name eks-cluster --region us-east-1
          kubectl cluster-info

      - name: Logar no Amazon ECR
        run: |
          AWS_REGION="us-east-1"
          AWS_ACCOUNT_ID=980921733871
          echo "Fazendo login no ECR da conta ${AWS_ACCOUNT_ID}..."
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.$AWS_REGION.amazonaws.com


      - name: Baixar a imagem do ECR
        run: |
          IMAGE_REPO="980921733871.dkr.ecr.us-east-1.amazonaws.com/fiapeats-ms-pedido:latest"
          docker pull $IMAGE_REPO


      - name: Substituir a versão da imagem no deployment.yaml
        run: |
          IMAGE_REPO="980921733871.dkr.ecr.us-east-1.amazonaws.com/fiapeats-ms-pedido:latest"
          sed -i "s|image: .*|image: $IMAGE_REPO|" kubernetes/deployment.yaml


      - name: Deploy no ambiente de produção
        run: |
          kubectl apply -f kubernetes/deployment.yaml
          kubectl apply -f kubernetes/ingress.yaml
          kubectl apply -f kubernetes/service.yaml
          kubectl apply -f kubernetes/configMap.yaml
          kubectl apply -f kubernetes/dashboard.yaml
          kubectl apply -f kubernetes/hpa.yaml
          kubectl apply -f kubernetes/metrics.yaml
          kubectl apply -f kubernetes/secrets.yaml
          kubectl apply -f kubernetes/service_eks.yaml
          kubectl apply -f kubernetes/userAdmin.yaml
      - name: Health Check após Deploy
        run: |
          kubectl rollout status deployment/fiapeats-ms-pedido-deployment -n default --timeout=5m
          kubectl get pods -n default